Adding files......
fipu-lab/movement-tracking pull request #1
Opened 2020-03-31 18:17 UTC by ssimic1144

2020-03-31 18:20 UTC, ssimic1144 commented
It should work . . .

2020-03-31 18:23 UTC, ntankovic requested changes
Najs!

2020-03-31 18:23 UTC, ntankovic commented on README.md
>  # movement-tracking
Napisati odakle je preuzeta baza projekta

2020-03-31 18:23 UTC, ntankovic commented on movement_tracking.py
> +if os.path.exists("movement_data.csv"):
Ovo bi trebalo ići u `--output` argument (ArgumentParser)

2020-04-01 10:07 UTC, samardzicmarko commented on movement_tracking.py
> +            fieldnames = ['timestamp', "id",'result']
Treba li nam "id" polje?

2020-04-01 10:51 UTC, ssimic1144 commented on movement_tracking.py
> +            fieldnames = ['timestamp', "id",'result']
"id" se koristi u calculate_movement()

2020-04-16 08:09 UTC, ntankovic approved these changes

2020-04-16 08:09 UTC, ntankovic commented on movement_tracking.py
> +    print(python)
Maknuti sve nepotrebne printove.

2020-04-16 08:09 UTC, merged